FROM ubuntu:20.04
ENV TZ=America/Toronto
LABEL authors="jaap@secureailabs.com"
USER root

# Set tzdata
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Install dependencies
RUN apt-get update && \
  apt-get -y upgrade && \
  apt-get install -y \
  nginx \
  wget \
  curl \
  sudo \
  build-essential \
  python3-pip


RUN pip install sail-fedops-local=1.0.0



ENTRYPOINT [ "/Entrypoint.sh" ]
# from
# RUN pip install sail-fedops-local=1.0.0

# build as
# docker build dockerfile_notebook

# Run the docker container
#docker run \
# -$detach \
#-p 8000:8001 \
#-p 9090:9091 \
#--env MODE=$mode \
#-v $mountOption \
#-v $(pwd)/certs:/etc/nginx/certs \
#$imageName
