name: Flake 8 and Black

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  pull_request:
    branches: [ main ]


jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: tonybajan/flake8-check-action@v1.0.0
      with:
        select: E402,E265,F841,F541,702
        maxlinelength: 120
        repotoken: ${{ secrets.GITHUB_TOKEN }}
